name: draw.io CLI
author: SevergroupTT
description: 'Export draw.io diagrams with drawio-desktop'

branding:
  color: orange
  icon: book-open

inputs:
  source:
    description: 'Input file/drectory name'
    required: true
  destination:
    destination: 'Output file/directory name'
    required: true
  format:
    description: 'Ouput file format'
    required: false
    default: 'svg'

runs:
  using: docker
  image: 'docker://ghcr.io/severgroup-tt/actions-drawio-cli:1.0.0'

